---
name: "Bethtest"

on: [push]


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - runs: |
          echo "::set-output name=foo::bar"

  notify-gem-released:
    needs: release
    runs-on: ubuntu-latest
    env:
      FOO: '${{ needs.release.outputs.foo }}'
    steps:
      - runs: "echo $FOO"
